//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWindowsFormAnalisisDeSistemas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public int Id { get; set; }
        public string marca { get; set; }
        public int precio { get; set; }
        public string color { get; set; }
    }
}
